### ISSUE TITLE
Should flatten batch regenerate the trace number?

### ISSUE THREAD

**Issue by tipputhynhean** [wadearnold/ach#1082]
ACH Version: `v1.19.2`

**What were you trying to do?**
Create file with `/files/create`
```json
{
	"fileHeader": {
		"immediateOrigin": "423423434",
		"immediateOriginName": "Testing Bank",
		"immediateDestination": "121042882",
		"immediateDestinationName": "JPMORGAN CHASE",
		"fileCreationDate": "220603",
		"fileCreationTime": "0330"
	},
	"batches": [
		{
			"batchHeader": {
				"serviceClassCode": 220,
				"companyName": "Testing Bank",
				"companyIdentification": "4234234",
				"standardEntryClassCode": "PPD",
				"companyEntryDescription": "PURCHASE",
				"effectiveEntryDate": "190102",
				"originatorStatusCode": 1,
				"ODFIIdentification": "12345678"
			},
			"entryDetails": [
				{
					"id": "",
					"transactionCode": 22,
					"RDFIIdentification": "12342343",
					"checkDigit": "8",
					"DFIAccountNumber": "9000286433423432",
					"amount": 8900,
					"identificationNumber": "USER",
					"individualName": "USER            ",
					"discretionaryData": "  "
				}
			]
		}
	]
}
```
then append batch with `files/{fileId}/batches`
```json
{
	"batchHeader": {
		"serviceClassCode": 220,
		"companyName": "Testing Bank",
		"companyIdentification": "4234234",
		"standardEntryClassCode": "PPD",
		"companyEntryDescription": "PURCHASE",
		"effectiveEntryDate": "190102",
		"originatorStatusCode": 1,
		"ODFIIdentification": "12345678"
	},
	"entryDetails": [
		{
			"id": "",
			"transactionCode": 22,
			"RDFIIdentification": "12342343",
			"checkDigit": "8",
			"DFIAccountNumber": "9000286433423432",
			"amount": 8900,
			"identificationNumber": "USER",
			"individualName": "USER            ",
			"discretionaryData": "  "
		}
	]
}
```
finally call flatten batch with `files/{fileId}/flatten`, we get this response
```json
{
	"error": "batch #1 (PPD) TraceNumber must be in ascending order, 123456780000001 is less than or equal to last number 123456780000001"
}
```

**What did you expect to see?**
Flatten batch should success and trace number get regenerated.

 This is probably depends on use case where we either want to regenerate or keep the trace number. I think there should be a query parameter or something that would allow this to be regenerated or not.

**Comment by adamdecaf** [comment]
I can reproduce this error and have an explanation of what's going on. 

First off the entry is created without a trace number so the library assigns one (`ODFIIdentification` plus sequence value) which is expected behavior. We do this so folks can add a bunch of entries and read the trace numbers afterwords. The second batch is added in the same manor but because it's in a second batch the sequence number starts over. This is probably a bug and trace numbers should be automatically assigned according to their sequence order within the file (instead of the batch). 

When flattening occurs that fails because the trace numbers were generated as the same value. We've said that Flatten / Merge operations on files will never modify the contents. If we started to modify trace numbers then callers who assigned a conflicting value would see malformed files (their trace numbers would change) and there'd be major bugs. Trace Numbers are often used as a primary method of looking up entries. 

The easiest fix for you is to either assign Trace Numbers or add the entries within a batch.
